version: '3.4'

services:
  app:
    container_name: web
    build: ./
    command: ./wait-for-postgres.sh db ./app
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
    env_file:
      - .env

  db:
    restart: always
    container_name: testdb
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432